version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
