services:
  graphc-neo4j:
    image: neo4j:5.26-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${DB_USER}/${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/neo4j/import
